version: '3.8'

# TODO: Add network
services:
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      env_file: ./.env
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_HOST: '${DB_HOST}'
        MYSQL_TCP_PORT: '${DB_PORT}'
        MYSQL_DATABASE: '${DB_NAME}'
        MYSQL_USER: '${DB_USER}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPY_PASSWORD: "1"
      healthcheck:
        test: ["CMD", "mysqladmin", "-u${DB_USER}", "-p${DB_PASSWORD}", "-h${DB_HOST}", "-P${DB_PORT}", "ping"]
        retries: 3
        timeout: 5s
      ports:
        - 3306:3306
      volumes:
        - ./.database:/var/lib/mysql
      networks:
        app:
          ipv4_address: 10.6.0.2

    core:
      build: ./src
      depends_on:
        db:
          condition: service_healthy
          restart: true
      volumes:
        - ./src:/app
      env_file: ./.env
      ports:
        - 8000:8000
      networks:
        app:
          ipv4_address: 10.6.0.3

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
